# Uncomment the next line to define a global platform for your project
platform :ios, '15.5'

target 'iosApp' do
  use_frameworks!
  pod 'shirmazApp', :path => '../shirmazApp'
  pod 'GoogleMLKit/PoseDetection', '7.0.0'
  pod 'GoogleMLKit/PoseDetectionAccurate', '7.0.0'

end
